version: '3'
services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
      - "2001:2001"
    volumes:
      - iobrokerdata:/opt/iobroker

  influxdb:
    restart: always
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
      - "2003:2003"
    env_file:
      - 'env.influxdb'
    volumes:
      - influxdbdata:/var/lib/influxdb2

  grafana:
    restart: always
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file:
      - 'env.grafana'
    user: "0"
    links:
      - influxdb
    volumes:
      - grafanadata:/var/lib/grafana

volumes:
  iobrokerdata:
  influxdbdata:
  grafanadata:
